### ISSUE TITLE
node_modules/import-from-esm/index"' has no default export

### ISSUE THREAD

**Issue by yordis** [sheerlox/import-from-esm#46]
Working on: https://github.com/straw-hat-team/nodejs-monorepo/pull/119/files

I had to do the following:

```ts
// @ts-expect-error
import importFrom from "import-from-esm";
``` 

Since for some reason the type system is confused:

```text
yarn build
src/openapi-web-sdk-generator.ts:2:8 - error TS1192: Module '"/Users/ubi/Developer/github.com/straw-hat-team/nodejs-monorepo/.yarn/cache/import-from-esm-npm-1.2.1-19132a3a23-17275e7d51.zip/node_modules/import-from-esm/index"' has no default export.

2 import importFrom from "import-from-esm";
         ~~~~~~~~~~


Found 1 error in src/openapi-web-sdk-generator.ts:2
```

Any thoughts?

**Comment by sheerlox** [comment]
Hey @yordis :wave: sorry for the delay, and thanks for reporting on the issue!

I've set up a minimum reproduction repository based on the one you linked, and successfully identified and fixed the issue in #48.

The fix is going to be released as [`v1.2.2`](https://github.com/sheerlox/import-from-esm/releases/tag/v1.2.2) in a few minutes :tada:
