### ISSUE TITLE
`exports` are not resolved correctly

### ISSUE THREAD

**Issue by 1aron** [sheerlox/import-from-esm#92]
As in Case 2 in https://github.com/semantic-release/commit-analyzer/issues/589, `import-from-esm` does not seem to resolve `exports` in package.json correctly.

> ### Case 2
> It's about my contribution semantic-release/commit-analyzer#588. Perform the following steps on latest master branch:
> 
> ```shell
> npm i conventional-changelog-techor@2.5.24 -D
> ```
> 
> Add the new `test/presets.test.js`
> 
> ```js
> import test from "ava";
> import { stub } from "sinon";
> import { analyzeCommits } from "../index.js";
> 
> const cwd = process.cwd();
> 
> test.beforeEach((t) => {
>   const log = stub();
>   t.context.log = log;
>   t.context.logger = { log };
> });
> 
> test('Accept "preset" option', async (t) => {
>   const commits = [
>     { hash: "123", message: "Fix: First fix (fixes #123)" },
>     { hash: "456", message: "Update: Second feature (fixes #456)" },
>   ];
>   const releaseType = await analyzeCommits({ preset: "techor" }, { cwd, commits, logger: t.context.logger });
> 
>   t.is(releaseType, null);
> });
> ```
> 
> ```shell
> npm test
> ```
> 
> ```shell
> > Cannot find module 'conventional-changelog-techor'
> ```
> 
> If I remove the `"exports": { ... }"` section from "node_modules/conventional-changelog-techor/package.json", it will work.
> 
> So this is a problem with `import-from-esm` itself, regardless of whether it is a monorepo or not.
> 
> When I change `import-from-esm` back to `import-from` everything still works. This means that the changes in v11.1 did not include tests for the new functionality (#537), and these tests would have failed before v11.1. Changes add a lot of uncertainty.

**Comment by sheerlox** [comment]
`import-from-esm` does support export maps and has a comprehensive test suite about them (see [`import-from-esm`'s tests/e2e.test.js](https://github.com/sheerlox/import-from-esm/blob/8fa4f0541426f9f4621dae92bb6fb6a4252b8d25/tests/e2e.test.js#L34-L38) and [`@insurgent/export-map-test`'s package.json](https://github.com/insurgent-lab/export-map-test/blob/f032290b05ed45db5ccef24ea51977d65057350c/package.json)).

Maybe the issue was caused by an incorrect export map, or more probably by the fact your package was dual-mode (CJS + ESM), which is not explicitly supported by `import-from-esm` as we haven't encountered any need for it yet.

I see you've removed both the export map and the dual-mode configuration from your package, and I'm guessing this solved your issue. If you're still encountering an issue, please feel free to reopen with more details about what the issue could be.
